In [1]:
#1. What is a Python library? 
#A Python library is a collection of pre-written code that provides
#specific functionality to help developers perform common tasks without
#having to write code from scratch. Libraries can include modules,
#functions, classes, and variables that can be imported and used in Python programs."""
#Why do we use Python libraries?
#1.Avoids rewriting common functions and algorithms.
#2.Speeds up development by providing ready-to-use solutions.
#3.Offers specialized tools for tasks like data analysis, web development,
#and machine learning.
#Benefits from extensive documentation and community contributions."""""

In [34]:
#3. Find the shape, size and dimension of the following array?

#solution
import numpy as np
arr_3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [35]:
#shape 
shape = np.shape(arr_3)
shape

(3, 4)

In [36]:
#size
size = np.size(arr_3)
size

12

In [37]:
#4. Write python code to access the first row of the following array?
arr_4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
first_row = arr_4[0]
first_row

array([1, 2, 3, 4])

In [39]:
#How do you access the element at the third row and fourth column from the given numpy array?
#Solution

arr_5 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
sol = arr_5[2,3]
sol

np.int64(12)

In [41]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
#Given data is 
arr_6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr_6[0:3,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [43]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.50395112, 0.70843593, 0.04764872],
       [0.70617385, 0.78118177, 0.50377495],
       [0.94039506, 0.02646962, 0.98200766]])

In [44]:
#8. Describe the difference between np.random.rand and np.random.randn?

     #solution
#np.random.rand: Generates random numbers from a uniform distribution in the range [0.0, 1.0).
#np.random.randn: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).


In [45]:
#9. Write code to increase the dimension of the following array?
#Given
arr_9 =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
arr_9.ndim

2

In [47]:
#Solution
dimension_increase = np.expand_dims(arr_9,axis=0)
dimension_increase


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [48]:
dimension_increase.ndim

3

In [49]:
#10. How to transpose the following array in NumPy?
#Given 
arr_10 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_10

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
#solution
trans = np.transpose(arr_10)
trans

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [51]:
#11. Consider the following matrix:

matrix_a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrix_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
matrix_b = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrix_b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
#Now Performing operations on matrix a and matix b
#1.Index wise multiplication
index_wise_mul = matrix_a * matrix_b
index_wise_mul

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [55]:
#2.Matrix multiplication
matrix_mul = np.dot(matrix_a,matrix_b.T)
matrix_mul

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [ ]:
#3. Add both the matrics
matrix_sum = matrix_a+matrix_b
matrix_sum

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [61]:
#4.Subtract matrix B from A
matrix_diff = matrix_b-matrix_a
matrix_diff

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
#5.Divide matix B by A
matrix_division = matrix_b/matrix_a
matrix_division

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])